import{a as m,S as ue,N as me,P as fe,R as J,i as R,b as G,A as V}from"./assets/vendor-BREOjyBh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();const ge="https://sound-wave.b.goit.study/api";m.defaults.baseURL=ge;const B=8;async function pe(){return(await m.get("/genres")).data}async function j(e={},t=1){const s={limit:B,page:t,...e},r=await m.get("/artists",{params:s});return{artists:r.data.artists,totalArtists:r.data.totalArtists}}async function be(e){return(await m.get(`/artists/${e}/albums`)).data}async function he(e=1){const t={limit:B,page:e};return(await m.get("/feedbacks",{params:t})).data.data}const ye=document.querySelectorAll(".arrow-btn");async function Le(){const e=document.querySelector(".swiper-wrapper");try{const t=[1,2,3];(await Promise.all(t.map(n=>he(n)))).flat().sort(()=>Math.random()-.5).slice(0,8).forEach(({descr:n,name:a,rating:d})=>{const f=document.createElement("div");f.classList.add("swiper-slide");const q=Math.round(d);f.innerHTML=`
      <div class="feedback-item">
        <div class="raty" data-score="${q}"></div>
        <p class="feedback-text">"${n}"</p>
        <p class="feedback-author">${a}</p>
      </div>
    `,e.appendChild(f)}),document.querySelectorAll(".raty").forEach(n=>{const a=n.dataset.score;new J(n,{starType:"i",score:a,readOnly:!0}).init()})}catch(t){console.error("Error fetching feedbacks:",t),e.innerHTML=`
      <div class="swiper-slide">
        <div class="feedback-item">
          <p class="feedback-text">Could not load reviews. Please try again later.</p>
        </div>
      </div>
    `,ye.forEach(s=>{s.style.display="none"})}}Le().then(()=>{new ue(".swiper",{modules:[me,fe],speed:400,spaceBetween:30,loop:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0,renderBullet:function(e,t){return`<span class="${t}"></span>`}}})});const b=document.querySelector(".artists-list"),$=document.querySelector(".modal"),g=document.querySelector(".backdrop-with-modal");document.querySelector(".artist-modal-list");const h=document.querySelector(".artists-pages"),ke=document.querySelector(".js-genres-list"),ve=document.querySelector(".filter-btn"),y=document.querySelector(".filters"),W=document.querySelector(".artists-not-found"),we=document.querySelectorAll(".js-reset-btn"),Y=document.querySelector(".modal-loader"),K=document.querySelector(".artists-loader"),z=document.querySelector(".modal-content"),Q=document.querySelector(".artist-list-wrapper");function Se(e){const t=Math.floor(e/1e3),s=Math.floor(t/60),r=t%60;return`${s}:${r<10?"0":""}${r}`}function H(e){return Math.ceil(e/B)}const L="/ArtistsHub/assets/sprite-24q4pASO.svg";function Ee(e){const{genres:t,strArtist:s,strArtistThumb:r,strBiographyEN:o,_id:n}=e;return`<li class="artist-card"> 
  
    <img  class="artist-thumb" src="${r}" alt="${s}">
    <ul class="artist-genres">
    ${Ae(t)}
    </ul>
    <h2 class="artist-name">${s}</h2>
    <p class="artist-biography">${o}</p>
    <button class="learn-more-btn" data-id="${n}">Learn More<svg width="24" height="24">
              <use href="${L}#icon-caret-right"></use>
            </svg></button>
    </li>`}function Ae(e){return e.map(s=>`<li class="genre-item">${s}</li>`).join("")}function I(e){const t=e.map(Ee).join("");b.innerHTML="",b.insertAdjacentHTML("beforeend",t)}function Ce(e){const t=e.map(({genre:s})=>`<li class="select-item">${s}</li>`).join("");ke.insertAdjacentHTML("beforeend",t)}function F(e,t){if(t===1){h.innerHTML="";return}if(e>t)return;let s="";const r=window.innerWidth;s+=`
    <a href="#artists-content" class="page-btn artists-arrow-btn" ${e===1?"disabled":""} data-page="${e-1}">
      <svg width="24" height="24">
        <use href="${L}#left-arrow-btn"></use>
      </svg>
    </a>
  `,s+=`<a href="#artists-content" class="page-btn ${e===1?"active":""}" data-page="1">1</a>`,(e>3||r<768&&e>2)&&(s+='<span class="dots">...</span>'),e>2&&r>=768&&(s+=`<a href="#artists-content" class="page-btn" data-page="${e-1}">${e-1}</a>`),e!==1&&e!==t&&(s+=`<a href="#artists-content" class="page-btn active" data-page="${e}">${e}</a>`),e<t-1&&r>=768&&(s+=`<a href="#artists-content" class="page-btn" data-page="${e+1}">${e+1}</a>`),(e<t-2||r<768&&t-1)&&(s+='<span class="dots">...</span>'),t>1&&(s+=`<a href="#artists-content" class="page-btn ${e===t?"active":""}" data-page="${t}">${t}</a>`),s+=`
    <a href="#artists-content" class="page-btn artists-arrow-btn" ${e===t?"disabled":""} data-page="${e+1}">
      <svg width="24" height="24">
        <use href="${L}#right-arrow-btn"></use>
      </svg>
    </a> 
  `,h.innerHTML=s}function qe(){Y.classList.remove("is-hidden")}function $e(){Y.classList.add("is-hidden")}function w(){K.classList.remove("is-hidden")}function S(){K.classList.add("is-hidden")}function Me(){z.classList.remove("is-hidden")}function Te(){z.classList.add("is-hidden")}function E(){Q.classList.remove("is-hidden")}function A(){Q.classList.add("is-hidden")}function xe(e){const{strArtist:t,strArtistThumb:s,intFormedYear:r,intDiedYear:o,strGender:n,intMembers:a,strCountry:d,strBiographyEN:f,genres:q,albumsList:re}=e,ne=$.querySelector(".modal-main-heading");ne.textContent=t;const oe=$.querySelector(".modal-artist-img");oe.src=s;const ae=document.querySelector(".js-modal-years");ae.textContent=o===null?`${r}-present`:`${r}-${o}`;const ie=document.querySelector(".js-modal-sex");ie.textContent=n;const ce=document.querySelector(".js-modal-members");ce.textContent=a;const le=document.querySelector(".js-modal-country");le.textContent=d;const de=document.querySelector(".js-modal-bio");de.textContent=f;const O=document.querySelector(".modal-info-genres-list");O.innerHTML="",O.insertAdjacentHTML("beforeend",Ne(q));const P=document.querySelector(".artist-modal-list");P.innerHTML="",P.insertAdjacentHTML("beforeend",Be(re))}function Ne(e){return e.map(s=>`<li class="modal-info-genre-li"><p class="modal-info-genre">${s}</p></li>`).join("")}function Be(e){return e.map(s=>je(s)).join("")}function je({strAlbum:e,tracks:t}){return`<li class="modal-table-li"><h2 class="artist-modal-album-title">${e}</h2>
                        <table class="artist-modal-album">
                            <thead>
                                <tr>
                                   <th class="position-left" scope="col">Track</th>
                                   <th scope="col">Time</th>
                                   <th scope="col">Link</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${He(t)}
                            </tbody>
                        </table></li>`}function He(e){return e.map(s=>Ie(s)).join("")}function Ie({strTrack:e,intDuration:t,movie:s}){const r=s?`<svg class="icon-modal-artist-track-list" width="24" height="24"><use href="${L}#youtube"></use></svg>`:"";return`<tr>
                        <td class="position-left track-name">${e}</td>
                        <td class="track-time ">${Se(t)}</td>
                        <td><a class="link-modal-artist-track-list" href="${s}">${r}</a></td>
                    </tr>`}let l=1,c={},U="",p=null;async function D(e,t){const{artists:s,totalArtists:r}=await j(e,t);if(r===0){b.innerHTML="",h.innerHTML="",W.classList.remove("visually-hidden");return}W.classList.add("visually-hidden"),I(s),F(t,H(r))}async function Fe(e){try{A(),w();const t=e.target.value.trim();if(t.length===U.length)return;U=t,t?c.name=t:delete c.name,l=1,await D(c,l)}catch(t){console.log(t)}finally{S(),E()}}async function De(e){try{if(e.target.closest(".select-btn")){const t=e.target.closest(".select-btn").nextElementSibling;t.classList.toggle("is-hidden"),p&&p!==t&&p.classList.add("is-hidden"),p=t;return}if(e.target.tagName==="LI"){const t=e.target.closest(".select"),s=t.querySelector(".select-input"),r=t.querySelector(".select-btn"),o=t.querySelector(".select-list-wrapper");if(s&&(s.value=e.target.textContent.trim()),r){const n=Array.from(r.childNodes).find(a=>a.nodeType===Node.TEXT_NODE);if(n){const a=e.target.textContent.trim();n.nodeValue=a;const d=t.dataset.selectName;d==="sortName"?a==="Default"?delete c.sortName:c={...c,[d]:a==="Z-A"?"desc":"asc"}:a==="All Genres"?delete c.genre:c={...c,[d]:a},l=1,A(),w(),await D(c,l)}}o&&o.classList.add("is-hidden")}}catch(t){console.log(t)}finally{S(),E()}}async function _e(e){const t=e.target.closest(".page-btn");if(!(!t||t.disabled||t.classList.contains("active")))try{const s=Number(t.dataset.page);if(s<1)return;l=s,A(),w();const{artists:r,totalArtists:o}=await j(c,l),n=H(o);I(r),F(l,n)}catch(s){console.log(s)}finally{S(),E()}}async function Oe(e){g.classList.add("is-open"),document.body.style.overflow="hidden",Te(),qe(),g.addEventListener("click",X),document.addEventListener("keydown",Z);try{const t=await be(e.target.dataset.id);xe(t)}catch(t){console.log(t)}finally{$e(),Me();const t=$.querySelector(".modal-info-text");t&&(t.scrollTop=0)}}function X(e){const t=e.target.closest(".modal-close-button"),s=e.target===g;(t||s)&&ee()}function Z(e){e.key==="Escape"&&ee()}function ee(){g.classList.remove("is-open"),document.body.style.overflow="",g.removeEventListener("click",X),document.removeEventListener("keydown",Z)}function Pe(e){e.target.closest(".filter-btn").nextElementSibling.classList.toggle("is-open")}function Re(e){c={},l=1;const t=y.querySelectorAll(".select-btn");t[0].childNodes[0].nodeValue="Sorting",t[1].childNodes[0].nodeValue="Genre",y.reset(),D(c,l)}const Ge="https://sound-wave.b.goit.study/api",Ve="/feedbacks",We=document.querySelector(".js-feedback-btn"),_=document.querySelector(".backdrop-feedback-modal"),i=document.querySelector(".feedback-modal-form"),Ue=document.querySelector(".js-feedback-modal-close-btn"),te=document.body,M=document.querySelector("[data-raty]"),T=i.querySelector('[data-error-for="name"]'),x=i.querySelector('[data-error-for="message"]'),N=i.querySelector('[data-error-for="rating"]'),k=i.elements.name,v=i.elements.message;//! Зірочки
const u=new J(M,{starType:"i",click(e){e>=1&&(M.classList.remove("feedback-modal-error"),N.textContent="")}});u.init();const Je=e=>m.post(`${Ge}${Ve}`,e);//! Валідація
const Ye=e=>(k.classList.remove("feedback-modal-error"),v.classList.remove("feedback-modal-error"),T.textContent="",x.textContent="",N.textContent="",!e.name||e.name.length<3?(k.classList.add("feedback-modal-error"),T.textContent="Name must be at least 3 characters long",!1):!e.descr||e.descr.length<10?(v.classList.add("feedback-modal-error"),x.textContent="Description must be at least 10 characters long",!1):!e.rating||e.rating<1?(M.classList.add("feedback-modal-error"),N.textContent="Please select a rating from 1 to 5",!1):!0),Ke=()=>{const e=k.value.trim(),t=v.value.trim();e.length>=3&&(k.classList.remove("feedback-modal-error"),T.textContent=""),t.length>=10&&(v.classList.remove("feedback-modal-error"),x.textContent="")},ze=async e=>{e.preventDefault();const t={name:i.elements.name.value.trim(),rating:u.score(),descr:i.elements.message.value.trim()};if(Ye(t)){console.log(t);try{const s=await Je(t);console.log(s),R.success({message:"Your feedback submited successfully",position:"topRight",color:"#9f7ab2"}),localStorage.removeItem("feedbackFormData"),i.reset(),u.score(0),C()}catch(s){console.log(s),R.error({message:"Error submitting feedback",position:"topRight",color:"#af4040"})}}},C=()=>{_.classList.remove("is-open"),te.classList.remove("no-scroll"),localStorage.removeItem("feedbackFormData"),i.reset(),u.score(0)},se=()=>{_.classList.add("is-open"),te.classList.add("no-scroll")},Qe=({key:e})=>{e==="Escape"&&C()},Xe=({target:e})=>{e===_&&C()},Ze=()=>{const e=localStorage.getItem("feedbackFormData");if(!e)return;const t=JSON.parse(e);se(),t&&(i.elements.name.value=t.name||"",i.elements.message.value=t.descr||"",t.rating&&u.score(t.rating))},et=()=>{const e={name:i.elements.name.value.trim(),descr:i.elements.message.value.trim(),rating:u.score()};localStorage.setItem("feedbackFormData",JSON.stringify(e))};//! Відкриття модалки
We.addEventListener("click",se);//! Закриття модалки
Ue.addEventListener("click",C);window.addEventListener("keydown",Qe);window.addEventListener("click",Xe);//! видалення помилки валідації при введенні полів
i.addEventListener("input",Ke);//! відправка на бекенд
i.addEventListener("submit",ze);//! збереження, видалення і отримання даних з LS
window.addEventListener("DOMContentLoaded",Ze);i.addEventListener("click",et);const tt=["./img/webp/default-webp-for-hero-slider/image-slider-01.webp","./img/webp/default-webp-for-hero-slider/image-slider-02.webp","./img/webp/default-webp-for-hero-slider/image-slider-03.webp","./img/webp/default-webp-for-hero-slider/image-slider-04.webp","./img/webp/default-webp-for-hero-slider/image-slider-05.webp"];document.querySelector(".splide__list");function st(){new G("#slider-left",{direction:"ttb",height:"500px",type:"loop",drag:!1,arrows:!1,pagination:!1,autoScroll:{speed:.5}}).mount({AutoScroll:V}),new G("#slider-right",{direction:"ttb",height:"500px",type:"loop",drag:!1,arrows:!1,pagination:!1,autoScroll:{speed:-.5}}).mount({AutoScroll:V})}function rt(e){const t=document.querySelector("#slider-left .splide__list"),s=document.querySelector("#slider-right .splide__list");t.innerHTML="",s.innerHTML="";const r=e.map(n=>`<li class="splide__slide">
              <img src="${n.strArtistThumb}" />
            </li>`).join(""),o=e.slice().reverse().map(n=>`<li class="splide__slide">
              <img src="${n.strArtistThumb}" />
            </li>`).join("");t.insertAdjacentHTML("beforeend",r),s.insertAdjacentHTML("beforeend",o),st()}function nt(e){const t=e.map(s=>s.strArtistThumb).filter(Boolean);return t.length===0?tt:t}const ot=()=>{const e=document.querySelector(".burger-btn"),t=document.querySelector(".cross-icon"),s=document.querySelector(".burger-icon"),r=document.querySelector(".menu-burger"),o=document.querySelector(".menu-burger"),n=()=>{console.log("toggle"),s.classList.toggle("hide"),t.classList.toggle("hide"),o.classList.toggle("hide")};e.addEventListener("click",n),r.addEventListener("click",a=>{console.log(a.target.tagName),(a.target.tagName==="LI"||a.target.tagName==="A")&&(console.log(a.target.tagName),n())})};ot();async function at(){A(),w();try{const{artists:e,totalArtists:t}=await j(),s=nt(e);rt(s.map(o=>({strArtistThumb:o}))),I(e);const r=await pe();F(1,H(t)),Ce(r)}catch(e){console.log(e)}finally{S(),E()}}at();y.addEventListener("input",Fe);y.addEventListener("click",De);h.addEventListener("click",_e);ve.addEventListener("click",Pe);we.forEach(e=>e.addEventListener("click",Re));b.addEventListener("click",e=>{e.target.closest(".learn-more-btn")&&Oe(e)});
//# sourceMappingURL=index.js.map
