import{a as u,S as z,N as Q,P as X,R as I,i as f,b as B,A as j}from"./assets/vendor-BREOjyBh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const Z="https://sound-wave.b.goit.study/api";u.defaults.baseURL=Z;const S=8;async function ee(){return(await u.get("/genres")).data}async function E(e={},t=1){const s={limit:S,page:t,...e},n=await u.get("/artists",{params:s});return{artists:n.data.artists,totalArtists:n.data.totalArtists}}async function te(e){return(await u.get(`/artists/${e}/albums`)).data}async function se(e=1){const t={limit:S,page:e};return(await u.get("/feedbacks",{params:t})).data.data}const ne=document.querySelectorAll(".arrow-btn");async function re(){const e=document.querySelector(".swiper-wrapper");try{const t=[1,2,3];(await Promise.all(t.map(o=>se(o)))).flat().sort(()=>Math.random()-.5).slice(0,8).forEach(({descr:o,name:i,rating:d})=>{const m=document.createElement("div");m.classList.add("swiper-slide");const v=Math.round(d);m.innerHTML=`
      <div class="feedback-item">
        <div class="raty" data-score="${v}"></div>
        <p class="feedback-text">"${o}"</p>
        <p class="feedback-author">${i}</p>
      </div>
    `,e.appendChild(m)}),document.querySelectorAll(".raty").forEach(o=>{const i=o.dataset.score;new I(o,{starType:"i",score:i,readOnly:!0}).init()})}catch(t){console.error("Error fetching feedbacks:",t),e.innerHTML=`
      <div class="swiper-slide">
        <div class="feedback-item">
          <p class="feedback-text">Could not load reviews. Please try again later.</p>
        </div>
      </div>
    `,ne.forEach(s=>{s.style.display="none"})}}re().then(()=>{new z(".swiper",{modules:[Q,X],speed:400,spaceBetween:30,loop:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0,renderBullet:function(e,t){return`<span class="${t}"></span>`}}})});const h=document.querySelector(".artists-list"),N=document.querySelector(".modal"),p=document.querySelector(".backdrop-with-modal");document.querySelector(".artist-modal-list");const y=document.querySelector(".artists-pages"),oe=document.querySelector(".js-genres-list"),ie=document.querySelector(".filter-btn"),L=document.querySelector(".filters"),H=document.querySelector(".artists-not-found"),ae=document.querySelectorAll(".js-reset-btn");function ce(e){const t=Math.floor(e/1e3),s=Math.floor(t/60),n=t%60;return`${s}:${n<10?"0":""}${n}`}function A(e){return Math.ceil(e/S)}const w="/ArtistsHub/assets/sprite-CJsgYEop.svg";function le(e){const{genres:t,strArtist:s,strArtistThumb:n,strBiographyEN:r,_id:o}=e;return`<li class="artist-card"> 
  
    <img  class="artist-thumb" src="${n}" alt="${s}">
    <ul class="artist-genres">
    ${de(t)}
    </ul>
    <h2 class="artist-name">${s}</h2>
    <p class="artist-biography">${r}</p>
    <button class="learn-more-btn" data-id="${o}">Learn More<svg width="24" height="24">
              <use href="${w}#icon-caret-right"></use>
            </svg></button>
    </li>`}function de(e){return e.map(s=>`<li class="genre-item">${s}</li>`).join("")}function $(e){const t=e.map(le).join("");h.innerHTML="",h.insertAdjacentHTML("beforeend",t)}function ue(e){const t=e.map(({genre:s})=>`<li class="select-item">${s}</li>`).join("");oe.insertAdjacentHTML("beforeend",t)}function M(e,t){if(t===1){y.innerHTML="";return}if(e>t)return;let s="";const n=window.innerWidth;s+=`
    <a href="#artists-content" class="page-btn artists-arrow-btn" ${e===1?"disabled":""} data-page="${e-1}">
      <svg width="24" height="24">
        <use href="${w}#left-arrow-btn"></use>
      </svg>
    </a>
  `,s+=`<a href="#artists-content" class="page-btn ${e===1?"active":""}" data-page="1">1</a>`,(e>3||n<768&&e>2)&&(s+='<span class="dots">...</span>'),e>2&&n>=768&&(s+=`<a href="#artists-content" class="page-btn" data-page="${e-1}">${e-1}</a>`),e!==1&&e!==t&&(s+=`<a href="#artists-content" class="page-btn active" data-page="${e}">${e}</a>`),e<t-1&&n>=768&&(s+=`<a href="#artists-content" class="page-btn" data-page="${e+1}">${e+1}</a>`),(e<t-2||n<768&&t-1)&&(s+='<span class="dots">...</span>'),t>1&&(s+=`<a href="#artists-content" class="page-btn ${e===t?"active":""}" data-page="${t}">${t}</a>`),s+=`
    <a href="#artists-content" class="page-btn artists-arrow-btn" ${e===t?"disabled":""} data-page="${e+1}">
      <svg width="24" height="24">
        <use href="${w}#right-arrow-btn"></use>
      </svg>
    </a> 
  `,y.innerHTML=s}function me(e){const{strArtist:t,strArtistThumb:s,intFormedYear:n,intDiedYear:r,strGender:o,intMembers:i,strCountry:d,strBiographyEN:m,genres:v,albumsList:P}=e,G=N.querySelector(".modal-main-heading");G.textContent=t;const W=N.querySelector(".modal-artist-img");W.src=s;const V=document.querySelector(".js-modal-years");V.textContent=r===null?`${n}-present`:`${n}-${r}`;const U=document.querySelector(".js-modal-sex");U.textContent=o;const Y=document.querySelector(".js-modal-members");Y.textContent=i;const J=document.querySelector(".js-modal-country");J.textContent=d;const K=document.querySelector(".js-modal-bio");K.textContent=m;const T=document.querySelector(".modal-info-genres-list");T.innerHTML="",T.insertAdjacentHTML("beforeend",fe(v));const x=document.querySelector(".artist-modal-list");x.innerHTML="",x.insertAdjacentHTML("beforeend",pe(P))}function fe(e){return e.map(s=>`<li class="modal-info-genre-li"><p class="modal-info-genre">${s}</p></li>`).join("")}function pe(e){return e.map(s=>ge(s)).join("")}function ge({strAlbum:e,tracks:t}){return`<li class="modal-table-li"><h2 class="artist-modal-album-title">${e}</h2>
                        <table class="artist-modal-album">
                            <thead>
                                <tr>
                                   <th scope="col">Track</th>
                                   <th scope="col">Time</th>
                                   <th scope="col">Link</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${be(t)}
                            </tbody>
                        </table></li>`}function be(e){return e.map(s=>he(s)).join("")}function he({strTrack:e,intDuration:t,movie:s}){const n=s?`<svg class="icon-modal-artist-track-list" width="24" height="24"><use href="${w}#youtube"></use></svg>`:"";return`<tr>
                        <td>${e}</td>
                        <td>${ce(t)}</td>
                        <td><a class="link-modal-artist-track-list" href="${s}">${n}</a></td>
                    </tr>`}let c=1,a={},F="",b=null;async function q(e,t){const{artists:s,totalArtists:n}=await E(e,t);if(n===0){h.innerHTML="",y.innerHTML="",H.classList.remove("visually-hidden");return}H.classList.add("visually-hidden"),$(s),M(t,A(n))}async function ye(e){try{const t=e.target.value.trim();if(t.length===F.length)return;F=t,t?a.name=t:delete a.name,c=1,q(a,c)}catch(t){console.log(t)}}async function Le(e){try{if(e.target.closest(".select-btn")){const t=e.target.closest(".select-btn").nextElementSibling;t.classList.toggle("is-hidden"),b&&b!==t&&b.classList.add("is-hidden"),b=t;return}if(e.target.tagName==="LI"){const t=e.target.closest(".select"),s=t.querySelector(".select-input"),n=t.querySelector(".select-btn"),r=t.querySelector(".select-list-wrapper");if(s&&(s.value=e.target.textContent.trim()),n){const o=Array.from(n.childNodes).find(i=>i.nodeType===Node.TEXT_NODE);if(o){const i=e.target.textContent.trim();o.nodeValue=i;const d=t.dataset.selectName;d==="sortName"?i==="Default"?delete a.sortName:a={...a,[d]:i==="Z-A"?"desc":"asc"}:i==="All Genres"?delete a.genre:a={...a,[d]:i},c=1,q(a,c)}}r&&r.classList.add("is-hidden")}}catch(t){console.log(t)}}async function we(e){const t=e.target.closest(".page-btn");if(!t||t.disabled||t.classList.contains("active"))return;const s=Number(t.dataset.page);if(s<1)return;c=s;const{artists:n,totalArtists:r}=await E(a,c),o=A(r);$(n),M(c,o)}async function ke(e){p.classList.add("is-open");const t=await te(e.target.dataset.id);me(t),document.body.style.overflow="hidden",p.addEventListener("click",_),document.addEventListener("keydown",D)}function _(e){const t=e.target.closest(".modal-close-button"),s=e.target===p;(t||s)&&R()}function D(e){e.key==="Escape"&&R()}function R(){p.classList.remove("is-open"),document.body.style.overflow="",p.removeEventListener("click",_),document.removeEventListener("keydown",D)}function ve(e){const t=e.target.closest(".filter-btn");t.nextElementSibling.style.display==="flex"?t.nextElementSibling.style.display="none":t.nextElementSibling.style.display="flex"}function Se(e){a={},c=1;const t=L.querySelectorAll(".select-btn");t[0].childNodes[0].nodeValue="Sorting",t[1].childNodes[0].nodeValue="Genre",L.reset(),q(a,c)}const Ee="https://sound-wave.b.goit.study/api",Ae="/feedbacks",$e=document.querySelector(".js-feedback-btn"),C=document.querySelector(".backdrop-feedback-modal"),l=document.querySelector(".feedback-modal-form"),Me=document.querySelector(".js-feedback-modal-close-btn"),O=document.body,qe=document.querySelector("[data-raty]");//! Зірочки
const g=new I(qe,{starType:"i"});g.init();const Ce=e=>u.post(`${Ee}${Ae}`,e);//! Валідація
const Te=e=>!e.name||e.name.length<3?(f.warning({message:"Name must be at least 3 characters long",position:"topRight",color:"#764191"}),!1):!e.descr||e.descr.length<10?(f.warning({message:"Description must be at least 10 characters long",position:"topRight"}),!1):e.rating===void 0?(f.warning({message:"Rating must be between 1 and 5",position:"topRight"}),!1):!0,xe=async e=>{e.preventDefault();const t={name:l.elements.name.value.trim(),rating:g.score(),descr:l.elements.message.value.trim()};if(console.log(t),!!Te(t)){console.log(t);try{const s=await Ce(t);console.log(s),f.success({message:"Your feedback submited successfully",position:"topRight"}),localStorage.removeItem("feedbackFormData"),l.reset(),g.score(0),k()}catch(s){console.log(s),f.error({message:"Error submitting feedback",position:"topRight"})}}},k=()=>{C.classList.remove("is-open"),O.classList.remove("no-scroll")},Be=()=>{C.classList.add("is-open"),O.classList.add("no-scroll")},je=({key:e})=>{e==="Escape"&&k()},Ne=({target:e})=>{e===C&&k()},He=()=>{const e=JSON.parse(localStorage.getItem("feedbackFormData"));e&&(l.elements.name.value=e.name||"",l.elements.message.value=e.descr||"",e.rating&&g.score(e.rating))},Fe=()=>{const e={name:l.elements.name.value.trim(),descr:l.elements.message.value.trim(),rating:g.score()};localStorage.setItem("feedbackFormData",JSON.stringify(e))};//! Відкриття модалки
$e.addEventListener("click",Be);//! Закриття модалки
Me.addEventListener("click",k);window.addEventListener("keydown",je);window.addEventListener("click",Ne);l.addEventListener("submit",xe);window.addEventListener("DOMContentLoaded",He);l.addEventListener("click",Fe);const Ie=["./img/webp/default-webp-for-hero-slider/image-slider-01.webp","./img/webp/default-webp-for-hero-slider/image-slider-02.webp","./img/webp/default-webp-for-hero-slider/image-slider-03.webp","./img/webp/default-webp-for-hero-slider/image-slider-04.webp","./img/webp/default-webp-for-hero-slider/image-slider-05.webp"];document.querySelector(".splide__list");function _e(){new B("#slider-left",{direction:"ttb",height:"500px",type:"loop",drag:!1,arrows:!1,pagination:!1,autoScroll:{speed:.5}}).mount({AutoScroll:j}),new B("#slider-right",{direction:"ttb",height:"500px",type:"loop",drag:!1,arrows:!1,pagination:!1,autoScroll:{speed:-.5}}).mount({AutoScroll:j})}function De(e){const t=document.querySelector("#slider-left .splide__list"),s=document.querySelector("#slider-right .splide__list");t.innerHTML="",s.innerHTML="";const n=e.map(o=>`<li class="splide__slide">
              <img src="${o.strArtistThumb}" />
            </li>`).join(""),r=e.slice().reverse().map(o=>`<li class="splide__slide">
              <img src="${o.strArtistThumb}" />
            </li>`).join("");t.insertAdjacentHTML("beforeend",n),s.insertAdjacentHTML("beforeend",r),_e()}function Re(e){const t=e.map(s=>s.strArtistThumb).filter(Boolean);return t.length===0?Ie:t}const Oe=()=>{const e=document.querySelector(".burger-btn"),t=document.querySelector(".cross-icon"),s=document.querySelector(".burger-icon"),n=document.querySelector(".menu-burger");e.addEventListener("click",()=>{s.classList.toggle("hide"),t.classList.toggle("hide"),n.classList.toggle("hide")})};Oe();async function Pe(){const{artists:e,totalArtists:t}=await E(),s=Re(e);De(s.map(r=>({strArtistThumb:r}))),$(e);const n=await ee();M(1,A(t)),ue(n)}Pe();L.addEventListener("input",ye);L.addEventListener("click",Le);y.addEventListener("click",we);ie.addEventListener("click",ve);ae.forEach(e=>e.addEventListener("click",Se));h.addEventListener("click",e=>{e.target.closest(".learn-more-btn")&&ke(e)});
//# sourceMappingURL=index.js.map
